apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: mern

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: poornimau/mern-backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 3500

        env:
        - name: MONGO_CONN_STR
          value: mongodb://mongodb:27017/todo

        - name: USE_DB_AUTH
          value: "false"
