name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Backend Dependencies
        working-directory: Application-Code/backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: Application-Code/frontend
        run: npm install

      - name: Build Frontend
        working-directory: Application-Code/frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:v1 ./Application-Code/backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:v1 ./Application-Code/frontend

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Backend Image
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/mern-backend:v1

      - name: Scan Frontend Image
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/mern-frontend:v1

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:v1

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name mern-eks-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f Application-Code/k8s/

      - name: Verify Deployment
        run: |
          kubectl get pods -n mern
          kubectl get svc -n mern
